### ISSUE TITLE
My Blender crashed if I sent same command to the port twice quickly 

### ISSUE THREAD

**Issue by rootaman** [p4vv37/blender_command_port#3] opened 2019-06-20 09:27 UTC
I was sending this command via Vocola extension to the port 5000 on my localhost: 
'import bpy; window = bpy.context.window;screen = window.screen;x = 944;y = 411;x = window.width+x if x < 0 else x;y = -1*y if y < 0 else window.height-y;area = next(area for area in bpy.context.screen.areas if area.type == 'VIEW_3D' and area.x < x and area.y < y and (area.width+area.x) > x and (area.height+area.y) > y);override = {'window': window, 'screen': screen, 'area': area, 'region': area.regions[4]};bpy.ops.view3D.toggle_xray(override)'.

It ran successful the first time but I sometimes call this command again and maybe it was too quick then my Blender Crashed.
SocketException : 
System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

I dont know if this is the issue from the addon or from my Vocola extension. If you need more info then I can provide it too...

**Comment by p4vv37** [comment] 2019-07-07 12:17
Hi
Right, this is probably a problem with blender_command_port, not Vocola.
There may be many reasons, that could result in this error, so please let me know if it is gone, but I've introduced some measures to prevent it:
* Shutdown is now used before closing connection and socket [this is why](https://docs.python.org/2/library/socket.html#socket.socket.close)
* Connection is retried 3 times before giving up, with asleep time ranging from 0 to .5s
* Added a 1s. timeout - if this was an issue with concurrency, this may help

I'll close this issue if you'll verify that it is fixed, if not, we'll go deeper

**Comment by rootaman** [comment] 2019-07-08 10:39
Please note that. I have to rename "USER_PREFERENCES" to "PREFERENCES" in the ___init___.py in order to make this new version load correctly in the newest 2.8 beta release.. I will try to test your new version by this week...

**Comment by p4vv37** [comment] 2019-07-09 06:07
Thank you, in 
blender-2.80-63ac7c799c8-linux-glibc224-x86_64 
that I was using it did still work, but in 
blender-2.80-a42cae160082-linux-glibc217-x86_64
it does not. I've submitted a change to fix that. Cons of working on plugins for beta version :)
In fact, this change make sense, I was confused by this name.

**Comment by rootaman** [comment] 2019-07-17 13:12
Well, I tested with 2.8RC there is no crash so far but the same command did work from Python console and Text Editor only. It did not work when sending from the Command Port now. Maybe it is a Blender issue because many of my command did not work with this RC. I think I will need more time to figure out why...

Aha, the "import bpy" need for every commands is no more..

**Comment by rootaman** [comment] 2019-07-17 13:52
Update: I switch back the addon to the previous version and all the commands work fine on 2.8RC so the problem might be from "something" in your recent version of the command port... the crash problem still be there but I can live with it since I have improve my command to NOT use the "override" with bpy.ops... method now because all the crashed commands are the one with "override" context thing in the command...but it is not easy for some kind of task to not use "override" context in Blender

**Comment by p4vv37** [comment] 2020-04-05 07:57
I really cannot reproduce it, but a lot has changed today, code is simpler.
Hope this helps
regards

**Closed as completed by p4vv37** 2020-04-05 07:57 UTC
